---
  - name: installing the httpd 
    hosts: dev,test
    tasks: 
        
      - name: insytalling the httpd
        ansible.biultin.dnf:
          name: httpd 
          state: present 

      - name: enable and start the httpd
        ansible.builtin.service:
          name: httpd 
          state: enabled 
      
      - name: start the httpd
        ansible.builtin.service:
          name: httpd 
          state: started
...
